language: python
python: 2.7
matrix:
  include:
  - env: stack=precise-container-filter
    sudo: false
    dist: precise
  - env: stack=precise-container-nofilter
    sudo: false
    dist: precise
    filter_secrets: false
  - env: stack=precise-sudo-filter
    dist: precise
    sudo: required
rvm:
  - 2.2
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/pip/wheels
branches:
  only:
  - master
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  global:
    - NODE_ENV=production
    - PIP_DISABLE_PIP_VERSION_CHECK=on
    - SENTRY_LIGHT_BUILD=1
    - SENTRY_SKIP_BACKEND_VALIDATION=1
    - TRAVIS_NODE_VERSION=4
    - CXX=g++-4.8
    - TEST_SUITE=dist
    - COLUMNS=1000
install:
  - nvm install 4
  - make travis-install-$TEST_SUITE
before_script:
  - pip freeze
  - ps -ejf --forest
  - ps xao pid,ppid,pgid,sid,tty,comm --forest
script:
  - make travis-lint-$TEST_SUITE
  - make travis-test-$TEST_SUITE
after_success:
  - codecov -e TEST_SUITE
  - ps -ejf --forest
  - ps xao pid,ppid,pgid,sid,tty,comm --forest
after_failure:
  - dmesg | tail -n 100
