language: python
python: 2.7
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  global:
    - PIP_DISABLE_PIP_VERSION_CHECK=on
    - SENTRY_LIGHT_BUILD=1
    - SENTRY_SKIP_BACKEND_VALIDATION=1
    - TRAVIS_NODE_VERSION=4
    - CXX=g++-4.8
    - TEST_SUITE=dist
    - COLUMNS=1000
matrix:
  include:
  - env: stack=precise-container-filter
    sudo: false
    dist: precise
  - env: stack=precise-sudo-filter
    dist: precise
    sudo: required
install:
  - nvm install 4
script: true
after_failure:
  - dmesg | tail -n 100
